In [1]:
import numpy as np

In [ ]:
product=np.dot(5,4)

In [ ]:
product

20

In [2]:
# product of 1D Array
# 1D array 
vector_a = 2 + 3j
vector_b = 4 + 5j
product=np.dot(vector_a,vector_b)

In [3]:
product

(-7+22j)

# How Code1 works ?

vector_a = 2 + 3j
vector_b = 4 + 5j

## now dot product
= 2(4 + 5j) + 3j(4 – 5j)

= 8 + 10j + 12j – 15

= -7 + 22j

In [4]:
vector_a = np.array([[1, 4], [5, 6]]) 
vector_b = np.array([[2, 4], [5, 2]]) 

In [5]:
vector_a

array([[1, 4],
       [5, 6]])

In [6]:
vector_b

array([[2, 4],
       [5, 2]])

In [ ]:
product = np.dot(vector_a, vector_b) 
print("Dot Product  : \n", product) 
#product

Dot Product  : 
 [[22 12]
 [40 32]]


In [ ]:
product = np.dot(vector_a, vector_b) 
print("Dot Product  : \n", product) 

Dot Product  : 
 [[22 12]
 [40 32]]


In [ ]:
product = np.dot(vector_b, vector_a) 
print("\nDot Product  : \n", product) 


Dot Product  : 
 [[22 32]
 [15 32]]


# References and Calculating Dot Product

https://courses.lumenlearning.com/ivytech-collegealgebra/chapter/finding-the-product-of-two-matrices/

In [7]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
vector

array([1, 2, 3, 4, 5, 6])

In [12]:
# Select third element of vector
vector[2]


3

In [15]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
# Select second row, second column
matrix[1,1]

5

In [ ]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [ ]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [19]:
# Select the last element
vector[-1]
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2],
       [4, 5]])

In [ ]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [28]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [23]:
# to view the shape of the matrix
matrix.shape


(3, 4)

In [ ]:
# View number of elements (rows * columns)
matrix.size

12

In [ ]:
# View number of dimensions
matrix.ndim

2

In [29]:
# Add 100 to all elements
matrix=matrix + 100
matrix

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [30]:
# Return maximum element
np.max(matrix)

112

In [31]:
# Return minimum element
np.min(matrix)

101

In [32]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([109, 110, 111, 112])

In [35]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([104, 108, 112])

In [36]:
# Return mean
np.mean(matrix)

106.5

In [37]:
# Return variance
np.var(matrix)

11.916666666666666

In [38]:
# Return standard deviation
np.std(matrix)

3.452052529534663

In [39]:
matrix.T

array([[101, 105, 109],
       [102, 106, 110],
       [103, 107, 111],
       [104, 108, 112]])

In [40]:
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# Flatten matrix
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Return matrix rank
The rank of a matrix is the dimensions of the vector space spanned by its columns or rows. Finding the rank of a matrix is easy in NumPy thanks to matrix_rank.



In [ ]:
np.linalg.matrix_rank(matrix)

2

# Calculating the Determinant
It can sometimes be useful to calculate the determinant of a matrix. NumPy makes this easy with det.

In [ ]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

np.linalg.det(matrix)

0.0

# Getting the Diagonal of a Matrix

NumPy makes getting the diagonal elements of a matrix easy with diagonal. It is also possible to get a diagonal off from the main diagonal by using the offset parameter:




In [42]:
# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [44]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)


array([2, 6])

In [ ]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

# Calculating the Trace of a Matrix

The trace of a matrix is the sum of the diagonal elements and is often used under the hood in machine learning methods. Given a NumPy multidimensional array, we can calculate the trace using trace. We can also return the diagonal of a matrix and calculate its sum:

In [ ]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
matrix.trace()

14

In [47]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

# Inverting a Matrix

The inverse of a square matrix, A, is a second matrix A–1, such that:

A A -1 = 1



In [ ]:
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix)


array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

# Generating Random Values


In [ ]:
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.73705122, 0.52336765, 0.32892658])

In [52]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)


array([6, 1, 3])

# Reference

https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html
